# Generated by Django 5.0.4 on 2025-04-17 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
    ]
