# Generated by Django 5.2 on 2025-04-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='scheduled_at',
        ),
    ]
