# Generated by Django 5.2 on 2025-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_event_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('buy_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('general', 'General'), ('VIP', 'VIP')], default='general', max_length=10)),
            ],
        ),
    ]
