# Generated by Django 5.2 on 2025-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
