# Generated by Django 5.2 on 2025-04-29 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ticket_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
