# Generated by Django 5.2 on 2025-05-01 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_rating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_ratings', to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_ratings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
