# Generated by Django 5.2 on 2025-05-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
        ('app', '0006_alter_notification_user'),
    ]

    operations = [
    ]
