# Generated by Django 5.2 on 2025-04-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticket_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_tickets', to='app.event'),
            preserve_default=False,
        ),
    ]
