# Generated by Django 5.2 on 2025-05-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ticket_evento'),
        ('app', '0008_refundrequest'),
    ]

    operations = [
    ]
