# Generated by Django 5.2 on 2025-05-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rating_evento_rating_usuario'),
        ('app', '0009_merge_0007_ticket_evento_0008_refundrequest'),
    ]

    operations = [
    ]
