# Generated by Django 5.2 on 2025-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20250502_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
