# Generated by Django 5.2 on 2025-05-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_location'),
        ('app', '0011_refundrequest_status'),
    ]

    operations = [
    ]
