# Generated by Django 5.2 on 2025-05-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='place',
        ),
    ]
