# Generated by Django 5.2 on 2025-05-18 17:37

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_location_event_place'),  # Ajustá esto si tu migración anterior tiene otro nombre
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, default='Título temporal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Descripción temporal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_at',
            field=models.DateTimeField(default='2000-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organized_events',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
       
    ]

#Los campos title, description, scheduled_at, y organizer usan valores por defecto solo para permitir la migración sin errores.

